name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  base:
    name: Prepare dependences
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Install dependencies"
        run: 
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements_test.txt

      - name: Upload Python dependencies as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: dependencies
          path: venv/

  black:
    name: Black codestyle
    runs-on: ubuntu-latest
    needs: base  # This job depends on 'install-deps'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Download Python dependencies from previous job
        uses: actions/download-artifact@v3
        with:
          name: dependencies

      - name: "Black codestyle check"
        run: 
          source venv/bin/activate
          black --check --diff .
