name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  PY_VERSION: "3.13"

jobs:
  base:
    name: Prepare dependences
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Install dependencies"
        run: |
          which python
          which python
          which python
          which python
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements_test.txt

      - name: "Cache dependencies"
        uses: actions/cache@v4.2.0
        with:
          path: venv
          key: ${{ runner.os }}-pip-dependencies-${{ hashFiles('requirements.txt') }}

  black:
    name: Black codestyle
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PY_VERSION}}

      - name: Restore Python virtual environment
        uses: actions/cache/restore@v4.2.0
        with:
          path: venv
          fail-on-cache-miss: true
          key: ${{ runner.os }}-pip-dependencies-${{ hashFiles('requirements.txt') }}

      - name: "Black codestyle check"
        run: |
          source venv/bin/activate
          black --check --diff .

  codespell:
    name: "Codespell check"
    runs-on: ubuntu-latest
    needs: base
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PY_VERSION}}

      - name: Restore Python virtual environment
        uses: actions/cache/restore@v4.2.0
        with:
          path: venv
          fail-on-cache-miss: true
          key: ${{ runner.os }}-pip-dependencies-${{ hashFiles('requirements.txt') }}

      - name: "Black codestyle check"
        run: |
          source venv/bin/activate
          ${{env.pythonLocation}}
          ${{env.pythonLocation}}
          ${{env.pythonLocation}}
          ${{env.pythonLocation}}
          ${{env.pythonLocation}}
          codespell --skip "*.pyc,*.pyi,*~,*.json,venv*" -L "hass"