name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  base:
    name: Prepare dependences
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: "Install dependencies"
        run: |
          python -m venv venv
          . venv/bin/activate
          echo "Where python: $pwd"
          pwd
          pwd
          which python
          which python
          pip install -r requirements_test.txt

      - name: "Cache dependencies"
        uses: actions/cache@v4.2.0
        with:
          path: venv
          key: ${{ runner.os }}-pip-dependencies-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-dependencies-

  black:
    name: Black codestyle
    runs-on: ubuntu-latest
    needs: base  # This job depends on 'install-deps'
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Restore Python virtual environment
        uses: actions/cache/restore@v4.2.0
        with:
          path: venv
          fail-on-cache-miss: true
          key: ${{ runner.os }}-pip-dependencies-${{ hashFiles('requirements.txt') }}

      - name: "Black codestyle check"
        run: |
          . venv/bin/activate
          which python
          echo "Where python: $pwd"
          pwd
          pwd
          which python
          which python
          black --check --diff .
